# Exercise 1:


In [ ]:
# Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.

In [2]:
import numpy as np

In [5]:
array1 = np.arange(1, 11)
reshaped_array = array1.reshape(2, 5)
print(reshaped_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# Exercise 2:

In [ ]:
# Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.

In [6]:
array2=np.arange(1,21)
extracted_elements = array2[5:15]
print(extracted_elements)

[ 6  7  8  9 10 11 12 13 14 15]


# Exercise 3:

In [ ]:
# Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' 
# and the value 4.

In [7]:
import pandas as pd

In [17]:
fruits = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
fruits

apples     3
bananas    2
oranges    1
dtype: int64

In [19]:
fruits['pears'] = 4
print("Updated Series:")
print(fruits)

Updated Series:
apples     3
bananas    2
oranges    1
pears      4
dtype: int64


# Exercise 4:

In [ ]:
# Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data. 

In [20]:
import pandas as pd

data = {
    'name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 
             'Frank', 'Grace', 'Hannah', 'Ian', 'Jack'],
    'age': [25, 30, 22, 28, 35, 40, 18, 27, 24, 33],
    'gender': ['Female', 'Male', 'Male', 'Female', 'Female', 
               'Male', 'Female', 'Female', 'Male', 'Male']
}

# Create a DataFrame
df = pd.DataFrame(data)

# Print the DataFrame
print("DataFrame:")
print(df)


DataFrame:
      name  age  gender
0    Alice   25  Female
1      Bob   30    Male
2  Charlie   22    Male
3    Diana   28  Female
4      Eve   35  Female
5    Frank   40    Male
6    Grace   18  Female
7   Hannah   27  Female
8      Ian   24    Male
9     Jack   33    Male


# Exercise 5:

In [ ]:
# Add a new column to the data frame created in  above question , called occupation. The values for this column should be Programmer, Manager, and
# Analyst, corresponding to the rows in the dataframe. 

In [21]:
# Add a new column 'occupation' with cyclic values
occupations = ['Programmer', 'Manager', 'Analyst']
df['occupation'] = [occupations[i % len(occupations)] for i in range(len(df))]

# Print the updated DataFrame
print("Updated DataFrame:")
print(df)

Updated DataFrame:
      name  age  gender  occupation
0    Alice   25  Female  Programmer
1      Bob   30    Male     Manager
2  Charlie   22    Male     Analyst
3    Diana   28  Female  Programmer
4      Eve   35  Female     Manager
5    Frank   40    Male     Analyst
6    Grace   18  Female  Programmer
7   Hannah   27  Female     Manager
8      Ian   24    Male     Analyst
9     Jack   33    Male  Programmer


# Exercise 6:

In [ ]:
# Select the rows of the dataframe where the age is greater than or equal to 30. 

In [22]:
filtered_df = df[df['age'] >= 30]
print("Rows where age is greater than or equal to 30:")
print(filtered_df)

Rows where age is greater than or equal to 30:
    name  age  gender  occupation
1    Bob   30    Male     Manager
4    Eve   35  Female     Manager
5  Frank   40    Male     Analyst
9   Jack   33    Male  Programmer


# Exercise 7:

In [ ]:
# Convert this dataframe to a csv file and read that csv file, finally display the contents.

In [23]:
csv_file = 'dataframe.csv'
df.to_csv(csv_file, index=False)

# Read the CSV file
df_from_csv = pd.read_csv(csv_file)

# Display the contents of the CSV file
print("Contents of the CSV file:")
print(df_from_csv)

Contents of the CSV file:
      name  age  gender  occupation
0    Alice   25  Female  Programmer
1      Bob   30    Male     Manager
2  Charlie   22    Male     Analyst
3    Diana   28  Female  Programmer
4      Eve   35  Female     Manager
5    Frank   40    Male     Analyst
6    Grace   18  Female  Programmer
7   Hannah   27  Female     Manager
8      Ian   24    Male     Analyst
9     Jack   33    Male  Programmer
